### ISSUE TITLE
How to add jar dependency

### ISSUE THREAD

**Issue by almozavr** [vanniktech/gradle-android-javadoc-plugin#22]
I'm using 
```
classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
```
to provide a `jitpack`-ready build.

The way it works – via method closure, aka
```
task sourcesJar(type: Jar) {
  classifier = 'sources'
  from android.sourceSets.main.java.srcDirs
}

task javadoc(type: Javadoc) {
  source = android.sourceSets.main.java.sourceFiles
  classpath += project.files(android.getBootClasspath().join(File.pathSeparator))

  options.memberLevel = JavadocMemberLevel.PROTECTED
  options.links("http://docs.oracle.com/javase/7/docs/api/")
  options.links("http://developer.android.com/reference/packages.html")
  exclude '**/BuildConfig.java'
  exclude '**/R.java'
  exclude '**/internal/**'
  failOnError false
}

task javadocJar(type: Jar, dependsOn: javadoc) {
  classifier = 'javadoc'
  from javadoc.destinationDir
}

artifacts {
  archives sourcesJar
  archives javadocJar
}
```

The problem is I can't figure out how to achieve the same with your plugin?
Even if I add a dependency for your task to `javadocJar` task, can't find a way to pass custom `destinationDir` to javadocJar's `from` property.
```
javadocJar.dependsOn {
  tasks.findAll { task -> task.name.contains('Javadoc') }
}
```

**Comment by vanniktech** [comment]
Well the task names are `generateDebugJavadoc` and `generateReleaseJavadoc`. So I don't think `tasks.findAll { task -> task.name.startsWith('Javadoc') }` works.

I've never actually tried what you're trying there so I can't think of any other reason. If you run the gradle tasks solely you do get the javadoc though, right?

**Comment by almozavr** [comment]
> task.name.startsWith

it's a type -> contains. 

Anyway, I'll get a javadoc, but not packed into the jar and even more there is no way for me to link it with maven release plugins (like`android-maven-gradle-plugin`)

**Comment by vanniktech** [comment]
The plugin generates a Html site containing the javadoc. e.g. [this one](https://cdn.rawgit.com/vanniktech/SparseBuilders/master/sparsebuilders/javaDoc/release/index.html)

I don't think you're even able to go and ship html documentation with a jar.

**Comment by almozavr** [comment]
> I don't think you're even able to go and ship html documentation with a jar.

Actually it's how it works:
![Actually it's how it works](https://monosnap.com/file/ZzadoriwtG0ebOaocDXwQzIh7jPVeR.png)

Nevermind, I just wanna check if you've faced with such situation.

**Comment by vanniktech** [comment]
Nope I didn't. If you find anything out or find a way to make it work feel free to comment it back here or open a PR if needed :)
