### ISSUE TITLE
Plugin inclusion error

### ISSUE THREAD

**Issue by Rufus125** [vanniktech/gradle-android-javadoc-plugin#4]
I can add the plugin as a dependency in my project build.gradle:
```xml
  classpath "gradle.plugin.com.vanniktech:gradle-android-javadoc-plugin:0.2.1"
```
However, when I apply the plugin in the module build.gradle:
apply plugin: 'com.vanniktech.android.javadoc'
 I get the following error message:
```
Error:(3, 0) Cause: com/vanniktech/android/javadoc/Generation : Unsupported major.minor version 52.0
```

**Comment by vanniktech** [comment]
The plugin is compiled with Java 8 and it seems like you're not running Java 8, hence you get that error message. 52.0 stands for Java 8. 

If you run it from Android Studio check that in the 'About Android Studio' dialog it says Java 8. If you run it from the terminal check that Gradle runs with Java 8. 

On 7 November 2015 23:12:43 CET, Rufus <notifications@github.com> wrote:
>I can add the plugin as a dependency in my project build.gradle:
>```xml
>classpath
>"gradle.plugin.com.vanniktech:gradle-android-javadoc-plugin:0.2.1"
>```
>However, when I apply the plugin in the module build.gradle:
>apply plugin: 'com.vanniktech.android.javadoc'
> I get the following error message:
>```
>Error:(3, 0) Cause: com/vanniktech/android/javadoc/Generation :
>Unsupported major.minor version 52.0
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/vanniktech/gradle-android-javadoc-plugin/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vanniktech** [comment]
Added the information about Java 8 to the README with 710a422a120cd40f51f005282dd32ce882450e8e
