### ISSUE TITLE
How can I set my javadoc_argfile ?

### ISSUE THREAD

**Issue by akidee** [vanniktech/gradle-android-javadoc-plugin#42]

**Comment by vanniktech** [comment]
I don't quite understand.

**Comment by akidee** [comment]
Before using your library (which works great so far because gradle resolves all the dependencies perfectly) I have used the javadoc command directly this way:

	javadoc \
	    -bootclasspath ~/Library/Android/sdk/platforms/android-25/android.jar:... \
	    -linkoffline https://developer.android.com/reference ~/Library/Android/sdk/docs/reference \
	    -d ~/software/java/doc/output \
	    @javadoc_in/javadoc_argfile

javadoc_argfile is a file with default javadoc options for my project which is just a list of regular javadoc options in a file. So I can customize my Javadoc with "-stylesheetfile", "-protected" or other options.

**Comment by vanniktech** [comment]
Hmm if there's something equivalent in Gradle we could make it work.

**Comment by akidee** [comment]
At least I d like to have a way to set any Javadoc option by hand. To use an argfile would be an easy way for you to accomplish this: You just need to add 1 additional option.

**Comment by vanniktech** [comment]
Alright sounds fair. I'll close this then in favor of #44
