### ISSUE TITLE
Where should I place customizations?

### ISSUE THREAD

**Issue by akidee** [vanniktech/gradle-android-javadoc-plugin#43]
Top-level build file:

	buildscript {
	    repositories {
	        jcenter()
	        mavenCentral() // retrolambda
	    }
	    dependencies {

	        // retrolambda: https://github.com/evant/gradle-retrolambda
	        classpath 'com.android.tools.build:gradle:2.3.3'
	        classpath 'me.tatarka:gradle-retrolambda:3.6.1'
	        // / retrolambda
	    }
	}

	allprojects {
	    repositories {
	        jcenter()
	        mavenCentral() // retrolambda
	    }
	}

Sub-project build file:

	apply plugin: 'com.android.library'

	android {
	    compileSdkVersion 25
	    buildToolsVersion "25.0.0"

	    defaultConfig {
	        minSdkVersion 9
	        targetSdkVersion 25
	        versionCode 1
	        versionName ""
	    }
	    compileOptions {
	        sourceCompatibility JavaVersion.VERSION_1_8
	        targetCompatibility JavaVersion.VERSION_1_8
	    }
	    buildTypes {
	        debug {
	            debuggable true
	            minifyEnabled false
	            useProguard false
	            shrinkResources false
	        }
	        release {
	            useProguard false
	            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
	        }
	    }
	}

	dependencies {
	    compile project(':subproject1')
	    compile project(':subproject2')
	    compile project(':subproject3')

	    ...
	    testCompile 'junit:junit:4.12'
	}

	// retrolambda
	apply plugin: 'me.tatarka.retrolambda'
	// / retrolambda

	buildscript {
	    repositories {
	        mavenCentral()
	    }
	    dependencies {
	        classpath 'com.vanniktech:gradle-android-javadoc-plugin:0.2.1'
	    }
	}

	apply plugin: 'com.vanniktech.android.javadoc'

	androidJavadoc {  // line 69
	    
	}

Result:

With the androidJavadoc{} block, I get this error:

    Error:(69, 0) Could not find method androidJavadoc() for arguments [akandroid_camera_6b8pdnwrdr764xdy7601utnpz$_run_closure3@71857546] on project ':akandroid_camera' of type org.gradle.api.Project.

I have placed androidJavadoc{} into different blocks, but I always get this error. Where must it be placed to make it work?

**Comment by vanniktech** [comment]
Place it after the apply plugin

**Comment by akidee** [comment]
I get the same error where ever I place it. BTW, the default place for Javadoc seems to be projectdir/javaDoc/ .

**Comment by vanniktech** [comment]
What's wrong with that destination?

**Comment by vanniktech** [comment]
I can't reproduce this.

**Comment by akidee** [comment]
Updated the issue description.

**Comment by vanniktech** [comment]
Oh I need to make another release. The README is ahead of the current version `0.2.1`. Try using the SNAPSHOT version.

**Comment by akidee** [comment]
Which repository must be added so that the artifact will be found? And how do I add it?

**Comment by vanniktech** [comment]
Snapshot repository. You can Google the link and add it with normal gradle syntax

**Comment by tir38** [comment]
@vanniktech can you go ahead and make another release? It took me some searching to get here. Or at least update readme?

**Comment by vanniktech** [comment]
Is the plugin working correctly with AGP 3.0?

**Comment by tir38** [comment]
Do you mean is 0.3.0-SNAPSHOT working with AGP 3.0? Aside from #45 then yes I think it is.

**Comment by vanniktech** [comment]
Alright cool. I'll try to get some time to make a release / enhance a few other things.
