### ISSUE TITLE
API variant.getAssemble() is obsolete

### ISSUE THREAD

**Issue by ewoks** [vanniktech/gradle-android-javadoc-plugin#66]
API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'

This is the error developer gets in Android Studio 3.3.0 when using gradle-android-javadoc-plugin:0.3.0 with com.android.tools.build:gradle:3.3.0

Is there possibility to fix it so it works with the newest stable Android Studio and gradle build tools plugin?

**Comment by ewoks** [comment]
@bastienpaulfr @vanniktech any clue how this could be fixed? I checked the code but no clue where to start :(

**Comment by vanniktech** [comment]
Similar to #65

We don't handle Configuration avoidance properly - https://docs.gradle.org/current/userguide/task_configuration_avoidance.html.

You'll get the same reply as in 65 - Mind submitting a PR? Frankly speaking, I haven't used this plugin in months.

**Comment by vanniktech** [comment]
This should be fixed now. Thanks to @bastienpaulfr
Can you try out the latest snapshot?
