### ISSUE TITLE
0.4.0-SNAPSHOT fails with Gradle 5.2.1 Android app SDK 28

### ISSUE THREAD

**Issue by smarek** [vanniktech/gradle-android-javadoc-plugin#68]
Hey, working on Simple-Dilbert, I tried to include your plugin instead of deprecated javadoc generation syntax.

0.3.0 does not fail, but does not generate any docs either (build/tmp/generateVariantJavadoc is empty, jar contains only MANIFEST.MF)
0.4.0-SNAPSHOT fails with "undefined symbol com.mareksebera.simpledilbert.R"

I've published my full build configuration here https://github.com/smarek/Simple-Dilbert/tree/javadoc

Running on host with OpenJDK 11 JRE+JDK only, Gradle 5.2.1

Could you maybe check, if that is your library or my build config issue?

Also your docs do not mention necessity of android>defaultConfig>versionCode/versionName properties (I used to have those only in AndroidManifest.xml), without those in build.gradle the javadoc is unnamed

Thank you

**Comment by vanniktech** [comment]
Interesting. To be honest, I've stopped using this plugin. Have you figured a way out? Depending on which AGP Version you're using we might need to change a thing or two

**Comment by smarek** [comment]
@vanniktech and what do you do use now?
I did not figured the way out. What is the "AGP Version" (Android Gradle Plugin?)

And for testing you can just clone the repository (branch javadoc), and try to build javadoc.
Usage of your plugin can be seen in the showcase commit https://github.com/smarek/Simple-Dilbert/commit/e0f2f3dcbc8b0c736b8762735982863237fbfdba

**Comment by vanniktech** [comment]
I've stopped using published javadoc's alltogether.

> What is the "AGP Version" (Android Gradle Plugin?)

Yup

I might have some time in the next days to look at your repository but don't get your hopes up

**Comment by smarek** [comment]
Thanks, fyi AGP is `classpath 'com.android.tools.build:gradle:3.4.1`

**Comment by vanniktech** [comment]
@smarek what's the status with AGP 4.0.0?

**Comment by smarek** [comment]
seems that javadoc generation is working, see https://github.com/android-async-http/android-async-http/releases/tag/1.4.11
and the PUBLISHING manual for the repo https://github.com/android-async-http/android-async-http/blob/master/PUBLISHING.md

However I need to manually run the task `gradle generateJavadocJar` to create appropriate javadoc files and pack them into JAR, but it seems to work with latest https://github.com/smarek/Simple-Dilbert/commit/182aa0622023560e8b1390d166925985ac5a0dfd so you can probably close the issue, if you don't want to investigate further
