### ISSUE TITLE
how to ignore "error: cannot find symbol" and continue generate javadoc

### ISSUE THREAD

**Issue by rils** [vanniktech/gradle-android-javadoc-plugin#71]
Hi,

I have some error, but it can be ignored. is there way to conitnue building java doc by ignoring any  "error: cannot find symbol"

**Comment by vanniktech** [comment]
You should probably fix them if there's an error.

**Comment by rils** [comment]
but when I generate manually from Android studio , It works - doc is generated. The errors were ignored.
